application: my-application
version: test

runtime: python27
api_version: 1
threadsafe: yes

builtins:
- django_wsgi: on

inbound_services:
- mail

libraries:
- name: lxml
  version: latest
- name: django
  version: latest

handlers:
- url: /favicon.ico
  static_files: trunk/static/favicon.ico
  upload: trunk/static/favicon.ico

- url: /robots.txt
  static_files: trunk/static/robots.txt
  upload: trunk/static/robots.txt

- url: /static/CACHE
  static_dir: trunk/compressor-static/CACHE

- url: /static
  static_dir: trunk/static

- url: /production_mediagenerator
  static_dir: trunk/_generated_media

- url: /__docs__/
  static_files: trunk/__docs__/index.html
  upload: trunk/__docs__/index.html
  login: admin

- url: /__docs__/
  static_dir: trunk/__docs__
  login: admin

- url: /__admin__/.*
  script: trunk.wsgi.application
  login: admin

- url: /?.*
  script: trunk.wsgi.application
#  login: required
#  secure: always
