version: 0.2

phases:
  install:
    #如果使用 Ubuntu 標準映像 2.0 或更新版本，您必須指定執行時間版本。
    #如果指定執行時間版本且使用非 Ubuntu 標準映像 2.0 的映像，建置會失敗。
    runtime-versions:
      python: 3.7
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - export COMMIT_CHANGESET=$(git rev-parse HEAD)
      - export BRANCH="$(git branch --points-at ${COMMIT_CHANGESET} )"
      - export SHORT_COMMIT_CHANGESET=$(git rev-parse --short=7 HEAD)
      - export BUILD_TIME=$(date +%Y-%m-%dT%H:%M:%S%z)
      - echo '{ "BRANCH"':' "'${BRANCH}'", \n  "CODEBUILD_BUILD_ID"':' "'${CODEBUILD_BUILD_ID}'",\n  "BUILD_TIME"':' "'${BUILD_TIME}'",\n   "COMMIT_CHANGESET"':' "'${COMMIT_CHANGESET}'" }' > s3_trunk/__version__.json
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - pip install -r requirements.txt
      - pip list
  build:
    commands:
      - cd docs/blog
      - tinker --build
      - cd ../../docs/www
      - make html
      - cd ../../s3_trunk
      - cp -rf ../docs/blog/blog/html blog
      - cp -rf ../docs/www/_build/html/* .
      - aws s3 cp --recursive . s3://twwww.hoamon.info/
  #post_build:
    #commands:
      # - command
      # - command
#artifacts:
  #files:
    #- jobs-ho600-com/*
  #secondary-artifacts:
    #promo:
      #files:
        #- promo-jobs-ho600-com/*
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
